package model

type ConsumerObject struct {
	TableName string
	Records   []string
}

type SourceObject struct {
	CODE      string
	TIME      string
	FIRST     string
	LAST      string
	DATE      string
	COLUMN_1  string
	COLUMN_2  string
	COLUMN_3  string
	COLUMN_4  string
	COLUMN_5  string
	COLUMN_6  string
	COLUMN_7  string
	COLUMN_8  string
	COLUMN_9  string
	COLUMN_10 string
	COLUMN_11 string
	COLUMN_12 string
	COLUMN_13 string
	COLUMN_14 string
	COLUMN_15 string
	COLUMN_16 string
	COLUMN_17 string
	COLUMN_18 string
	COLUMN_19 string
	COLUMN_20 string
	COLUMN_21 string
	COLUMN_22 string
	COLUMN_23 string
	COLUMN_24 string
	COLUMN_25 string
	COLUMN_26 string
	COLUMN_27 string
	COLUMN_28 string
	COLUMN_29 string
	COLUMN_30 string
	COLUMN_31 string
	COLUMN_32 string
	COLUMN_33 string
	COLUMN_34 string
	COLUMN_35 string
	COLUMN_36 string
	COLUMN_37 string
	COLUMN_38 string
	COLUMN_39 string
	COLUMN_40 string
	COLUMN_41 string
	COLUMN_42 string
	COLUMN_43 string
	COLUMN_44 string
	COLUMN_45 string
	COLUMN_46 string
	COLUMN_47 string
	COLUMN_48 string
	COLUMN_49 string
	COLUMN_50 string
	COLUMN_51 string
	COLUMN_52 string
	COLUMN_53 string
	COLUMN_54 string
	COLUMN_55 string
	COLUMN_56 string
	COLUMN_57 string
	COLUMN_58 string
	COLUMN_59 string
	COLUMN_60 string
	COLUMN_61 string
	COLUMN_62 string
	COLUMN_63 string
	COLUMN_64 string
	COLUMN_65 string
	COLUMN_66 string
	COLUMN_67 string
	COLUMN_68 string
	COLUMN_69 string
	COLUMN_70 string
	COLUMN_71 string
	COLUMN_72 string
}
